export const PHRASES = {
  LOADING: 'Loading...',
  NO_RESULTS: 'No results...',
  TICK_TEXT_SUNNY: 'Sunny',
  TICK_TEXT_RAINY: 'Rainy',
  TICK_TEXT_HEAVY_RAIN: 'Heavy Rain',
  TODAY: 'Today',
  WEEK: 'Week',
  TEMPERATURE_CHART: 'Temperature Chart',
  TIME: 'Time',
  DAYS: 'Days',
  PRECIPITATION: 'Precipitation',
  CHANCE_OF_PRECIPITATION: 'Chance of Precipitation',
  SEARCH_CITY: 'Search city ...',
  MIN_TEMPERATURE: 'Min Temperature',
  MAX_TEMPERATURE: 'Max Temperature',
  TODAYS_HIGHLIGHTS: `Today's Highlights`,
  RELATIVE_HUMIDITY: 'Relative Humidity',
  WIND: 'Wind',
  SUNRISE_SUNSET: 'Sunrise & Sunset',
  TREE_DAYS_FORECAST: '3 Days Forecast',
  WEATHER_FORECAST: 'Weather Forecast',
};
