export const weatherIconData = {
  icon0: 'Clear sky',
  icon1: 'Mainly clear',
  icon2: 'Partly cloudy',
  icon3: 'Overcast',
  icon45: 'Fog',
  icon48: 'Depositing rime fog',
  icon51: 'Light Drizzle',
  icon53: 'Moderate Drizzle',
  icon55: 'Dense intensity Drizzle',
  icon56: 'Light Freezing Drizzle',
  icon57: 'Dense intensity Freezing Drizzle',
  icon61: 'Slight Rain',
  icon63: 'Moderate Rain',
  icon65: 'Heavy intensity Rain',
  icon66: 'Light Freezing Rain',
  icon67: 'Heavy intensity Freezing Rain',
  icon71: 'Slight Snow fall',
  icon73: 'Moderate Snow fall',
  icon75: 'Heavy intensity Snow fall',
  icon77: 'Snow grains',
  icon80: 'Slight Rain showers',
  icon81: 'Moderate Rain showers',
  icon82: 'Violent Rain showers',
  icon85: 'Snow showers slight',
  icon86: 'Snow showers heavy',
  icon95: 'Thunderstorm: Slight or moderate',
  icon96: 'Thunderstorm with slight hail',
  icon99: 'Thunderstorm with heavy hail',
};
