export const SET_CITIES = 'SET_CITIES';
export const ADD_CITY = 'ADD_CITY';
export const REMOVE_CITY = 'REMOVE_CITY';
export const GET_CURRENT_CITY = 'GET_CURRENT_CITY';
export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
// export const SET_SEARCH_CITIES = 'SET_SEARCH_CITIES';

// export const GET_SEARCH_CITIES_REQUEST = 'GET_SEARCH_CITIES_REQUEST';
// export const GET_SEARCH_CITIES_SUCCESS = 'GET_SEARCH_CITIES_SUCCESS';
// export const GET_SEARCH_CITIES_FAILURE = 'GET_SEARCH_CITIES_FAILURE';
