export const SET_SEARCH_CITIES = 'SET_SEARCH_CITIES';

export const GET_SEARCH_CITIES_REQUEST = 'GET_SEARCH_CITIES_REQUEST';
export const GET_SEARCH_CITIES_SUCCESS = 'GET_SEARCH_CITIES_SUCCESS';
export const GET_SEARCH_CITIES_FAILURE = 'GET_SEARCH_CITIES_FAILURE';
